[package]
name = "penrose"
version = "0.1.10"
edition = "2018"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
license = "MIT"
repository = "https://github.com/sminez/penrose"
documentation = "https://docs.rs/penrose"
readme = "README.md"
description = """
A tiling window manager library/WM for X11 in the style of dwm and Xmonad.
"""

[features]
default = ["draw"]
draw = ["cairo-rs", "cairo-sys-rs", "pango", "pangocairo"]

[dependencies]
anyhow = "1.0.32"
nix = "0.17.0"
log = "0.4.8"
xcb = { version = "0.9.0", features = ["randr"] }

cairo-rs = { version = "0.9.1", features = ["xcb"], optional = true }
cairo-sys-rs = { version = "0.10.0", optional = true }
pangocairo = { version = "0.10.0", optional = true }
pango = { version = "0.9.1", optional = true }

[dev-dependencies]
simplelog = "0.8.0"
